name: flutter_detect_pitch
description: "A Flutter plugin for real-time pitch detection using the device microphone with native audio processing for iOS and Android."
version: 0.0.1+1
homepage: https://github.com/felix-ml/pitch_detector
repository: https://github.com/felix-ml/pitch_detector
issue_tracker: https://github.com/felix-ml/pitch_detector/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.felixml.flutter_detect_pitch
        pluginClass: FlutterDetectPitchPlugin
      ios:
        pluginClass: FlutterDetectPitchPlugin
